### ISSUE TITLE
Is it possible to add multi-threading to improve CPU performance?

### ISSUE THREAD

**Issue by WOLFxxxxxx** [c-krit/ferox#25]

**Comment by jdeokkim** [comment]
Hello, thank you for your interest in my project!

I really appreciate your suggestion, but unfortunately, I'm not planning to add multi-threading support for now, since this library was made for educational purposes (e.g. for undergraduate students like me who are interested in how a physics engine works).

If you are looking for a high-performance 2D physics engine, I recommend you to take a look at the following projects:
- [Box2D](https://github.com/erincatto/box2d)
- [Chipmunk2D](https://github.com/slembcke/Chipmunk2D)
- [JoltPhysics](https://github.com/jrouwe/JoltPhysics)
- [Rapier](https://github.com/dimforge/rapier)

If you're not satisfied with those options, I recommend you to check out the official [Box2D Discord server](https://box2d.org/about) and ask for advices there! 👍
